version: "3.7"
services:
  postgres:
    ports:
      - 5432:5432
    image: postgres:14.12-bullseye
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    networks:
      postgres-admin:

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: imchibitouka@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_LISTEN_PORT: 5050 
    networks:
      postgres-admin:
    ports:
      - 5050:5050

networks:
  postgres-admin:
    name: postgres-admin
    ipam:
      driver: default